resources:
  - account.yaml
  - role.yaml
  - git-key.yaml
  - deployment.yaml
  - memcached.yaml
configMapGenerator:
  - name: flux-kube-config
    files:
      - kubeconfig.yaml
images:
  - name: weaveworks/flux
    newTag: 1.13.1
  - name: memcached
    newTag: 1.5.15